--------------------------------------------------------
-- 1. 모든 테이블 삭제 (자식 -> 부모 순서로 삭제)
--------------------------------------------------------
DROP TABLE TB_STORY_ITEM;
DROP TABLE TB_NOTIFICATION;
DROP TABLE TB_ACCOUNT_HISTORY;
DROP TABLE TB_STORY_VISITOR;
DROP TABLE TB_STORY_ITEM;
DROP TABLE TB_REPORT_COMMENT;
DROP TABLE TB_COMMENT_LIKE;
DROP TABLE TB_COMMENT;
DROP TABLE TB_GUESTBOOK_LIKE;
DROP TABLE TB_GUESTBOOK;
DROP TABLE TB_DM_READ_STATUS;
DROP TABLE TB_DM_MESSAGE;
DROP TABLE TB_DM_PARTICIPANT;
DROP TABLE TB_DM_ROOM;
DROP TABLE TB_PAYMENT;
DROP TABLE TB_REPORT_FEED;
DROP TABLE TB_FEED_BOOKMARK;
DROP TABLE TB_FEED_LIKE;ㅈ
DROP TABLE TB_FEED_FILE;
DROP TABLE TB_FOLLOWS;
DROP TABLE TB_HOME_VISITOR;
DROP TABLE TB_DIARY;
DROP TABLE TB_STORY;
DROP TABLE TB_FEED;
DROP TABLE TB_MEMBER_HOME;
DROP TABLE TB_BGM;
DROP TABLE TB_MEMBER;

--------------------------------------------------------
-- 2. 모든 시퀀스 삭제
--------------------------------------------------------
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_HISTORY_NO;
DROP SEQUENCE SEQ_HOME_NO;
DROP SEQUENCE SEQ_FEED_NO;
DROP SEQUENCE SEQ_IMAGE_NO;
DROP SEQUENCE SEQ_REPORT_FEED_ID;
DROP SEQUENCE SEQ_BGM_NO;
DROP SEQUENCE SEQ_PAYMENT_NO;
DROP SEQUENCE SEQ_DM_ROOM_ID;
DROP SEQUENCE SEQ_DM_MESSAGE_ID;
DROP SEQUENCE SEQ_DM_READ_NO;
DROP SEQUENCE SEQ_GUESTBOOK_NO;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_COMMENT_LIKE_NO;
DROP SEQUENCE SEQ_REPORT_ID;
DROP SEQUENCE SEQ_STORY_NO;
DROP SEQUENCE SEQ_STORY_ITEM_NO;
DROP SEQUENCE SEQ_DIARY_NO;
DROP SEQUENCE SEQ_BOOKMARK_NO;
DROP SEQUENCE SEQ_NOTIFICATION_NO;

--------------------------------------------------------
-- 3. 시퀀스 생성
--------------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HISTORY_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HOME_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FEED_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_IMAGE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPORT_FEED_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BGM_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DM_ROOM_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DM_MESSAGE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DM_READ_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GUESTBOOK_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_LIKE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPORT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_STORY_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_STORY_ITEM_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DIARY_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOOKMARK_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NOTIFICATION_NO START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------------
-- 4. 테이블 생성 (부모 -> 자식 순서)
--------------------------------------------------------

-- 1. 회원 테이블
CREATE TABLE TB_MEMBER (
    MEMBER_NO           NUMBER          PRIMARY KEY,
    MEMBER_ID           VARCHAR2(20)    UNIQUE NOT NULL,
    MEMBER_PWD          VARCHAR2(100)   NOT NULL,
    MEMBER_NAME         VARCHAR2(50)    NOT NULL,
    MEMBER_NICK         VARCHAR2(50)    UNIQUE,
    EMAIL               VARCHAR2(250)   UNIQUE,
    PHONE               VARCHAR2(13),
    GENDER              CHAR(1),
    BIRTHDAY            DATE,
    CREATE_DATE         DATE            DEFAULT SYSDATE,
    STATUS              CHAR(1)         DEFAULT 'N'
);

-- 2. 계정 내역 (히스토리)
CREATE TABLE TB_ACCOUNT_HISTORY (
    HISTORY_NO      NUMBER          PRIMARY KEY,
    MEMBER_NO       NUMBER          NOT NULL,
    EVENT_TYPE      VARCHAR2(50)    NOT NULL,
    EVENT_DESC      VARCHAR2(300),
    EVENT_DATE      DATE            DEFAULT SYSDATE,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO) ON DELETE CASCADE
);

-- 3. 홈피 테이블
CREATE TABLE TB_MEMBER_HOME (
    HOME_NO             NUMBER          PRIMARY KEY,
    HOME_TITLE          VARCHAR2(50),
    STATUS_MSG          VARCHAR2(500),
    PROFILE_ORIGIN_NAME VARCHAR2(200),
    PROFILE_CHANGE_NAME VARCHAR2(200),
    IS_PRIVATE_PROFILE  CHAR(1)         DEFAULT 'N',
    IS_PRIVATE_VISIT    CHAR(1)         DEFAULT 'N',
    IS_PRIVATE_FOLLOW   CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          UNIQUE NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 4. 피드 테이블
CREATE TABLE TB_FEED (
    FEED_NO         NUMBER          PRIMARY KEY,
    CONTENT         VARCHAR2(200),
    TAG             VARCHAR2(20),
    LATITUDE        NUMBER(10,6),
    LONGITUDE       NUMBER(10,6),
    PLACE_NAME      VARCHAR2(100),
    KAKAO_PLACE_ID  VARCHAR2(50),
    ADDRESS_NAME    VARCHAR2(200),
    ROAD_ADDRESS    VARCHAR2(200),
    LOCATION_NAME   VARCHAR2(200),
    CREATED_DATE    DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 5. BGM 테이블
CREATE TABLE TB_BGM (
    BGM_NO           NUMBER          PRIMARY KEY,
    BGM_TITLE       VARCHAR2(200),
    FILE_PATH       VARCHAR2(250),
    ARTIST          VARCHAR2(100),
    PRICE           NUMBER,
    REG_DATE         DATE            DEFAULT SYSDATE
);

-- 6. DM 대화방 테이블
CREATE TABLE TB_DM_ROOM (   
    ROOM_NO     NUMBER      PRIMARY KEY, 
    CREATE_DATE DATE        DEFAULT SYSDATE
);

-- 5-1. DM 참여자 테이블 (누가 이 방에 참여하는지)
CREATE TABLE TB_DM_PARTICIPANT (	
    ROOM_NO                 NUMBER NOT NULL, 
    MEMBER_ID               VARCHAR2(50 BYTE) NOT NULL, 
    LAST_READ_MESSAGE_NO    NUMBER, 
    JOINED_AT               DATE DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ROOM_NO, MEMBER_ID)  -- 복합 키로 변경
);



-- 6. 스토리 테이블
CREATE TABLE TB_STORY (
    STORY_NO         NUMBER          PRIMARY KEY,
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    EXPIRE_DATE     DATE,
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(500),
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 8-1. 스토리 아이템 테이블 (통합됨)
CREATE TABLE TB_STORY_ITEM (
  ITEM_NO      NUMBER        PRIMARY KEY,
  STORY_NO     NUMBER        NOT NULL,
  ITEM_ORDER   NUMBER        NOT NULL,
  ORIGIN_NAME  VARCHAR2(200),
  CHANGE_NAME  VARCHAR2(200),
  FILE_PATH    VARCHAR2(500),
  STORY_TEXT   VARCHAR2(300),
  IS_DEL       CHAR(1) DEFAULT 'N' CHECK (IS_DEL IN ('Y','N')),
  CREATE_DATE  DATE DEFAULT SYSDATE,
  CONSTRAINT FK_STORY_ITEM_STORY FOREIGN KEY (STORY_NO) REFERENCES TB_STORY (STORY_NO),
  CONSTRAINT UQ_STORY_ITEM_ORDER UNIQUE (STORY_NO, ITEM_ORDER)
);

-- 9. 다이어리 테이블
CREATE TABLE TB_DIARY (
    DIARY_NO         NUMBER          PRIMARY KEY,
    TITLE           VARCHAR2(50),
    CONTENT         VARCHAR2(2100),
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(200),
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 10. 홈피 방문자 테이블
CREATE TABLE TB_HOME_VISITOR (
    VISIT_DATE      DATE            DEFAULT SYSDATE,
    MEMBER_NO       NUMBER          NOT NULL,
    HOME_NO         NUMBER          NOT NULL,
    PRIMARY KEY (MEMBER_NO, HOME_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 11. 팔로우 테이블
CREATE TABLE TB_FOLLOWS (
    MEMBER_NO       NUMBER          NOT NULL,
    HOME_NO         NUMBER          NOT NULL,
    STATUS          CHAR(1)         DEFAULT 'Y', -- 'Y': 승인, 'P': 대기
    PRIMARY KEY (MEMBER_NO, HOME_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 12. 피드 첨부 파일
CREATE TABLE TB_FEED_FILE (
    IMAGE_NO         NUMBER          PRIMARY KEY,
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(500),
    UPLOAD_DATE     DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    FEED_NO         NUMBER          NOT NULL,
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 13. 피드 좋아요
CREATE TABLE TB_FEED_LIKE (
    FEED_NO         NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    PRIMARY KEY (FEED_NO, MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 14. 피드 북마크
CREATE TABLE TB_FEED_BOOKMARK (
    BOOKMARK_NO     NUMBER          PRIMARY KEY,
    FEED_NO         NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 15. 피드 신고
CREATE TABLE TB_REPORT_FEED (
    REPORT_ID       NUMBER          PRIMARY KEY,
    REPORT_REASON   VARCHAR2(250),
    REPORT_DATE     DATE            DEFAULT SYSDATE,
    PROCESS_DATE    DATE,
    MEMBER_NO       NUMBER          NOT NULL,
    FEED_NO         NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 16. 결제 테이블
CREATE TABLE TB_PAYMENT (
    PAYMENT_NO      NUMBER          PRIMARY KEY,
    PAYMENT_AMOUNT  NUMBER,
    PAYMENT_DATE    DATE            DEFAULT SYSDATE,
    BGM_NO          NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (BGM_NO) REFERENCES TB_BGM(BGM_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 17. DM 메시지 테이블
CREATE TABLE TB_DM_MESSAGE (
    MESSAGE_NO      NUMBER              PRIMARY KEY, 
    ROOM_NO         NUMBER              NOT NULL, 
    SENDER_ID       VARCHAR2(50)   NOT NULL, 
    CONTENT         VARCHAR2(4000), 
    CREATE_DATE     DATE                DEFAULT SYSDATE, 
    IS_DEL          CHAR(1)         DEFAULT 'N',
    FOREIGN KEY (ROOM_NO) REFERENCES TB_DM_ROOM(ROOM_NO)
);

-- 18. DM 메시지 읽음 상태
CREATE TABLE TB_DM_READ_STATUS (
    READ_NO         NUMBER              PRIMARY KEY,
    ROOM_NO         NUMBER              NOT NULL,
    READER_ID       VARCHAR2(50)   NOT NULL,
    LAST_READ_DATE  DATE                DEFAULT SYSDATE,
    UNIQUE(ROOM_NO, READER_ID),
    FOREIGN KEY (ROOM_NO) REFERENCES TB_DM_ROOM(ROOM_NO)
);

-- 19. 방명록 테이블
CREATE TABLE TB_GUESTBOOK (
    GUESTBOOK_NO        NUMBER          PRIMARY KEY,
    GUESTBOOK_CONTENT   VARCHAR2(4000)  NOT NULL,
    CREATE_DATE         DATE            DEFAULT SYSDATE,
    IS_DEL              CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          NOT NULL,
    HOME_NO             NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 20. 방명록 좋아요
CREATE TABLE TB_GUESTBOOK_LIKE (
    MEMBER_NO       NUMBER          NOT NULL,
    GUESTBOOK_NO    NUMBER          NOT NULL,
    PRIMARY KEY (MEMBER_NO, GUESTBOOK_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (GUESTBOOK_NO) REFERENCES TB_GUESTBOOK(GUESTBOOK_NO)
);

-- 21. 댓글 테이블
CREATE TABLE TB_COMMENT (
    COMMENT_NO      NUMBER          PRIMARY KEY,
    CONTENT         VARCHAR2(250),
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    WRITER          NUMBER          NOT NULL,
    FEED_NO         NUMBER          NOT NULL,
    FOREIGN KEY (WRITER) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 22. 댓글 좋아요
CREATE TABLE TB_COMMENT_LIKE (
    COMMENT_LIKE_NO NUMBER          PRIMARY KEY,
    COMMENT_NO      NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    FOREIGN KEY (COMMENT_NO) REFERENCES TB_COMMENT(COMMENT_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 23. 댓글 신고
CREATE TABLE TB_REPORT_COMMENT (
    REPORT_ID       NUMBER          PRIMARY KEY,
    REPORT_REASON   VARCHAR2(50),
    REPORT_DATE     DATE            DEFAULT SYSDATE,
    PROCESS_DATE    DATE,
    MEMBER_NO       NUMBER          NOT NULL,
    COMMENT_NO      NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (COMMENT_NO) REFERENCES TB_COMMENT(COMMENT_NO)
);

-- 6. 스토리 테이블
CREATE TABLE TB_STORY (
    STORY_NO         NUMBER          PRIMARY KEY,
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    EXPIRE_DATE     DATE,
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(500),
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 24. 스토리 방문자
CREATE TABLE TB_STORY_VISITOR (
    MEMBER_NO       NUMBER          NOT NULL,
    STORY_NO         NUMBER          NOT NULL,
    PRIMARY KEY (MEMBER_NO, STORY_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (STORY_NO) REFERENCES TB_STORY(STORY_NO)
);

-- 스토리 테이블 추가(여러 사진 모음)
CREATE TABLE TB_STORY_ITEM (
  ITEM_NO      NUMBER        NOT NULL,
  STORY_NO     NUMBER        NOT NULL,
  ITEM_ORDER   NUMBER        NOT NULL,
  ORIGIN_NAME  VARCHAR2(200),
  CHANGE_NAME  VARCHAR2(200),
  FILE_PATH    VARCHAR2(500),
  STORY_TEXT   VARCHAR2(300),
  IS_DEL       CHAR(1) DEFAULT 'N' CHECK (IS_DEL IN ('Y','N')),
  CREATE_DATE  DATE DEFAULT SYSDATE,
  CONSTRAINT PK_STORY_ITEM PRIMARY KEY (ITEM_NO),
  CONSTRAINT FK_STORY_ITEM_STORY FOREIGN KEY (STORY_NO)
    REFERENCES TB_STORY (STORY_NO)
);

CREATE SEQUENCE SEQ_STORY_ITEM_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ALTER TABLE TB_STORY_ITEM
  --ADD CONSTRAINT UQ_STORY_ITEM_ORDER UNIQUE (STORY_NO, ITEM_ORDER);



-- 25. 알림 테이블
CREATE TABLE TB_NOTIFICATION (
    NOTIFICATION_NO NUMBER          PRIMARY KEY,
    RECEIVER_NO     NUMBER          NOT NULL,
    SENDER_NO       NUMBER          NOT NULL,
    TYPE            VARCHAR2(20)    NOT NULL,
    TARGET_ID       NUMBER,
    IS_READ         CHAR(1)         DEFAULT 'N',
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    FOREIGN KEY (RECEIVER_NO) REFERENCES TB_MEMBER(MEMBER_NO) ON DELETE CASCADE,
    FOREIGN KEY (SENDER_NO) REFERENCES TB_MEMBER(MEMBER_NO) ON DELETE CASCADE
);

COMMIT;