-- 1. 모든 시퀀스 삭제 (DROP SEQUENCES)

DROP SEQUENCE SEQ_DIARY_NO;
DROP SEQUENCE SEQ_STORY_NO;
DROP SEQUENCE SEQ_REPORT_ID;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_GUESTBOOK_NO;
DROP SEQUENCE SEQ_DM_MESSAGE_ID;
DROP SEQUENCE SEQ_DM_ROOM_ID;
DROP SEQUENCE SEQ_PAYMENT_NO;
DROP SEQUENCE SEQ_BGM_NO;
DROP SEQUENCE SEQ_REPORT_FEED_ID;
DROP SEQUENCE SEQ_IMAGE_NO;
DROP SEQUENCE SEQ_FEED_NO;
DROP SEQUENCE SEQ_HOME_NO;


-- 2. 모든 테이블 삭제 (DROP TABLES - 역순)
-- 외래 키 제약 조건을 고려하여 의존성이 낮은 테이블부터 삭제합니다.

DROP TABLE TB_STORY_VISITOR;       -- TB_STORY, TB_MEMBER 참조
DROP TABLE TB_REPORT_COMMENT;      -- TB_COMMENT, TB_MEMBER 참조
DROP TABLE TB_COMMENT;             -- TB_FEED, TB_MEMBER 참조
DROP TABLE TB_GUESTBOOK_LIKE;      -- TB_GUESTBOOK, TB_MEMBER 참조
DROP TABLE TB_GUESTBOOK;           -- TB_MEMBER_HOME, TB_MEMBER 참조
DROP TABLE TB_DM_MESSAGE;          -- TB_DM_ROOM, TB_MEMBER 참조
DROP TABLE TB_DM_ROOM;             -- TB_MEMBER 참조
DROP TABLE TB_PAYMENT;             -- TB_BGM, TB_MEMBER 참조
DROP TABLE TB_REPORT_FEED;         -- TB_FEED, TB_MEMBER 참조
DROP TABLE TB_FEED_LIKE;           -- TB_FEED, TB_MEMBER 참조
DROP TABLE TB_FEED_FILE;           -- TB_FEED 참조
DROP TABLE TB_FOLLOWS;             -- TB_MEMBER_HOME, TB_MEMBER 참조
DROP TABLE TB_HOME_VISITOR;        -- TB_MEMBER_HOME, TB_MEMBER 참조
DROP TABLE TB_DIARY;               -- TB_MEMBER 참조
DROP TABLE TB_STORY;               -- TB_MEMBER 참조
DROP TABLE TB_FEED;                -- TB_MEMBER 참조
DROP TABLE TB_MEMBER_HOME;         -- TB_MEMBER 참조 (1:1 관계)
DROP TABLE TB_BGM;
DROP TABLE TB_MEMBER;

-- TB_MEMBER_HOME의 HOME_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_HOME_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_FEED의 FEED_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_FEED_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_FEED_FILE의 IMAGE_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_IMAGE_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_REPORT_FEED의 REPORT_ID를 위한 시퀀스
CREATE SEQUENCE SEQ_REPORT_FEED_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_BGM의 BGM_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_BGM_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_PAYMENT의 PAYMENT_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_PAYMENT_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_DM_ROOM의 ROOM_ID를 위한 시퀀스
CREATE SEQUENCE SEQ_DM_ROOM_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_DM_MESSAGE의 MESSAGE_ID를 위한 시퀀스
CREATE SEQUENCE SEQ_DM_MESSAGE_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_GUESTBOOK의 GUESTBOOK_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_GUESTBOOK_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_COMMENT의 COMMENT_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_COMMENT_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_REPORT_COMMENT의 REPORT_ID를 위한 시퀀스
CREATE SEQUENCE SEQ_REPORT_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_STORY의 STORY_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_STORY_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- TB_DIARY의 DIARY_NO를 위한 시퀀스
CREATE SEQUENCE SEQ_DIARY_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 1. TB_MEMBER (회원 테이블)
CREATE TABLE TB_MEMBER (
    MEMBER_NO           NUMBER          PRIMARY KEY,
    MEMBER_ID           VARCHAR2(20)    UNIQUE NOT NULL,
    MEMBER_PWD          VARCHAR2(100)   NOT NULL,
    MEMBER_NAME         VARCHAR2(50)    NOT NULL,
    MEMBER_NICK         VARCHAR2(50)    UNIQUE,
    EMAIL               VARCHAR2(250)   UNIQUE,
    PHONE               VARCHAR2(13),
    GENDER              CHAR(1),
    BIRTHDAY            DATE,
    CREATE_DATE         DATE            DEFAULT SYSDATE,
    STATUS              CHAR(1)         DEFAULT 'N'
);

-- 2. TB_MEMBER_HOME (홈피 테이블 - 1:1 관계)
CREATE TABLE TB_MEMBER_HOME (
    HOME_NO             NUMBER          PRIMARY KEY,
    HOME_TITLE          VARCHAR2(50),
    STATUS_MSG          VARCHAR2(500),
    PROFILE_ORIGIN_NAME VARCHAR2(200),
    PROFILE_CHANGE_NAME VARCHAR2(200),
    IS_PRIVATE_PROFILE  CHAR(1)         DEFAULT 'N',
    IS_PRIVATE_VISIT    CHAR(1)         DEFAULT 'N',
    IS_PRIVATE_FOLLOW   CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          UNIQUE NOT NULL,

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 3. TB_FEED (피드/게시글 테이블)
CREATE TABLE TB_FEED (
    FEED_NO         NUMBER          PRIMARY KEY,
    CONTENT         VARCHAR2(200),
    TAG             VARCHAR2(20),
    LATITUDE        VARCHAR2(20),
    LONGITUDE       VARCHAR2(20),
    CREATED_DATE    DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'Y',
    MEMBER_NO       NUMBER          NOT NULL,

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 4. TB_BGM (BGM 테이블)
CREATE TABLE TB_BGM (
    BGM_NO          NUMBER          PRIMARY KEY,
    BGM_TITLE       VARCHAR2(200),
    FILE_PATH       VARCHAR2(250),
    ARTIST          VARCHAR2(100),
    PRICE           NUMBER,
    REG_DATE        DATE            DEFAULT SYSDATE
);

-- 5. TB_DM_ROOM (DM 대화방 테이블)
CREATE TABLE TB_DM_ROOM (
    ROOM_ID             NUMBER          PRIMARY KEY,
    LAST_SEND_DATE      DATE,
    IS_DEL              CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          NOT NULL,  -- 방 만든 회원
    MEMBER_NO2          NUMBER          NOT NULL,  -- 초대된 회원

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (MEMBER_NO2) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 6. TB_STORY (스토리 테이블)
CREATE TABLE TB_STORY (
    STORY_NO        NUMBER          PRIMARY KEY,
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    EXPIRE_DATE     DATE,
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(500),
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 7. TB_DIARY (다이어리 테이블)
CREATE TABLE TB_DIARY (
    DIARY_NO        NUMBER          PRIMARY KEY,
    TITLE           VARCHAR2(50),
    CONTENT         VARCHAR2(2100),
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(200),
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 8. TB_HOME_VISITOR (홈피 방문자 테이블 - N:M 관계)
CREATE TABLE TB_HOME_VISITOR (
    VISIT_DATE      DATE            DEFAULT SYSDATE,
    MEMBER_NO       NUMBER          NOT NULL,  -- 방문자
    HOME_NO         NUMBER          NOT NULL,  -- 방문당한 홈피

    PRIMARY KEY (MEMBER_NO, HOME_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 9. TB_FOLLOWS (팔로우 테이블 - N:M 관계)
CREATE TABLE TB_FOLLOWS (
    MEMBER_NO       NUMBER          NOT NULL,  -- 팔로우 하는 회원
    HOME_NO         NUMBER          NOT NULL,  -- 팔로우 당하는 홈피

    PRIMARY KEY (MEMBER_NO, HOME_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 10. TB_FEED_FILE (피드 첨부 파일 테이블)
CREATE TABLE TB_FEED_FILE (
    IMAGE_NO        NUMBER          PRIMARY KEY,
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(500),
    UPLOAD_DATE     DATE,
    IS_DEL          CHAR(1),
    FEED_NO         NUMBER          NOT NULL,

    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 11. TB_FEED_LIKE (피드 좋아요 테이블 - N:M 관계)
CREATE TABLE TB_FEED_LIKE (
    FEED_NO         NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,

    PRIMARY KEY (FEED_NO, MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 12. TB_REPORT_FEED (피드 신고 테이블)
CREATE TABLE TB_REPORT_FEED (
    REPORT_ID       NUMBER          PRIMARY KEY,
    REPORT_REASON   VARCHAR2(250),
    REPORT_DATE     DATE            DEFAULT SYSDATE,
    PROCESS_DATE    DATE,
    MEMBER_NO       NUMBER          NOT NULL,  -- 신고한 사람
    FEED_NO         NUMBER          NOT NULL,  -- 신고 당한 피드

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 13. TB_PAYMENT (결제 테이블)
CREATE TABLE TB_PAYMENT (
    PAYMENT_NO      NUMBER          PRIMARY KEY,
    PAYMENT_AMOUNT  NUMBER,
    PAYMENT_DATE    DATE            DEFAULT SYSDATE,
    BGM_NO          NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,

    FOREIGN KEY (BGM_NO) REFERENCES TB_BGM(BGM_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 14. TB_DM_MESSAGE (DM 메시지 테이블)
CREATE TABLE TB_DM_MESSAGE (
    MESSAGE_ID      NUMBER          PRIMARY KEY,
    CONTENT         VARCHAR2(1500),
    SEND_DATE       DATE            DEFAULT SYSDATE,
    IS_READ         CHAR(1)         DEFAULT 'N',
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,  -- 보낸 회원
    MEMBER_NO2      NUMBER          NOT NULL,  -- 받은 회원
    ROOM_ID         NUMBER          NOT NULL,

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (MEMBER_NO2) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (ROOM_ID) REFERENCES TB_DM_ROOM(ROOM_ID)
);

-- 15. TB_GUESTBOOK (방명록 테이블)
CREATE TABLE TB_GUESTBOOK (
    GUESTBOOK_NO        NUMBER          PRIMARY KEY,
    GUESTBOOK_CONTENT   VARCHAR2(4000)  NOT NULL,
    CREATE_DATE         DATE            DEFAULT SYSDATE,
    IS_DEL              CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          NOT NULL,  -- 작성한 회원 (방문자)
    HOME_NO             NUMBER          NOT NULL,  -- 방명록이 남겨진 홈피

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 16. TB_GUESTBOOK_LIKE (방명록 좋아요 테이블 - N:M 관계)
CREATE TABLE TB_GUESTBOOK_LIKE (
    MEMBER_NO       NUMBER          NOT NULL,
    GUESTBOOK_NO    NUMBER          NOT NULL,

    PRIMARY KEY (MEMBER_NO, GUESTBOOK_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (GUESTBOOK_NO) REFERENCES TB_GUESTBOOK(GUESTBOOK_NO)
);

-- 17. TB_COMMENT (댓글 테이블)
CREATE TABLE TB_COMMENT (
    COMMENT_NO      NUMBER          PRIMARY KEY,
    CONTENT         VARCHAR2(250),
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    WRITER          NUMBER          NOT NULL,  -- 작성자
    FEED_NO        NUMBER          NOT NULL,  -- 피드 번호

    FOREIGN KEY (WRITER) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 18. TB_REPORT_COMMENT (댓글 신고 테이블)
CREATE TABLE TB_REPORT_COMMENT (
    REPORT_ID       NUMBER          PRIMARY KEY,
    REPORT_REASON   VARCHAR2(50),
    REPORT_DATE     DATE            DEFAULT SYSDATE,
    PROCESS_DATE    DATE,
    MEMBER_NO       NUMBER          NOT NULL,  -- 신고한 사람
    COMMENT_NO      NUMBER          NOT NULL,  -- 신고 당한 댓글

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (COMMENT_NO) REFERENCES TB_COMMENT(COMMENT_NO)
);

-- 19. TB_STORY_VISITOR (스토리 방문자 테이블 - N:M 관계)
CREATE TABLE TB_STORY_VISITOR (
    MEMBER_NO       NUMBER          NOT NULL,  -- 방문자
    STORY_NO        NUMBER          NOT NULL,  -- 방문한 스토리

    PRIMARY KEY (MEMBER_NO, STORY_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (STORY_NO) REFERENCES TB_STORY(STORY_NO)
);

--------------------------------------------------------

drop table tb_dm_room;
drop table tb_dm_message;


-- 테이블 수정본
CREATE TABLE TB_DM_ROOM (
    ROOM_NO         NUMBER PRIMARY KEY,
    ROOM_TYPE       VARCHAR2(10) DEFAULT 'PRIVATE',  -- 'PRIVATE' / 'GROUP'
    ROOM_NAME       VARCHAR2(100),                   -- 그룹방 이름 (선택)
    CREATE_DATE     DATE DEFAULT SYSDATE,
    LAST_SEND_DATE  DATE DEFAULT SYSDATE,
    IS_DEL          CHAR(1) DEFAULT 'N'
    
    -- ❌ MEMBER_NO, MEMBER_NO2 제거 (별도 테이블로 이동)
    -- ❌ LAST_READ_NO1, LAST_READ_NO2 제거 (별도 테이블로 이동)
);

CREATE TABLE TB_DM_ROOM_MEMBER (
    ROOM_MEMBER_NO  NUMBER PRIMARY KEY,              -- PK
    ROOM_NO         NUMBER NOT NULL,                 -- FK → TB_DM_ROOM
    MEMBER_NO       NUMBER NOT NULL,                 -- FK → TB_MEMBER
    JOINED_DATE     DATE DEFAULT SYSDATE,            -- 참여일
    LAST_READ_NO    NUMBER DEFAULT 0,                -- 마지막 읽은 메시지 번호
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',             -- 방 나가기 여부
    
    CONSTRAINT FK_ROOM_MEMBER_ROOM FOREIGN KEY (ROOM_NO) REFERENCES TB_DM_ROOM(ROOM_NO),
    CONSTRAINT FK_ROOM_MEMBER_USER FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

CREATE TABLE TB_DM_MESSAGE (
    MESSAGE_NO      NUMBER PRIMARY KEY,
    ROOM_NO         NUMBER NOT NULL,                 -- FK → TB_DM_ROOM
    MEMBER_NO       NUMBER NOT NULL,                 -- 보낸 사람
    CONTENT         VARCHAR2(1500),
    SEND_DATE       DATE DEFAULT SYSDATE,
    IS_DEL          CHAR(1) DEFAULT 'N',
    
    CONSTRAINT FK_DM_MSG_ROOM FOREIGN KEY (ROOM_NO) REFERENCES TB_DM_ROOM(ROOM_NO),
    CONSTRAINT FK_DM_MSG_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);