--------------------------------------------------------
-- 1. 모든 테이블 삭제 (외래키 제약조건 고려, 자식 -> 부모 순)
--------------------------------------------------------
DROP TABLE TB_STORY_VISITOR;
DROP TABLE TB_REPORT_COMMENT;
DROP TABLE TB_COMMENT_LIKE;
DROP TABLE TB_COMMENT;
DROP TABLE TB_GUESTBOOK_LIKE;
DROP TABLE TB_GUESTBOOK;
DROP TABLE TB_DM_MESSAGE;
DROP TABLE TB_DM_ROOM;
DROP TABLE TB_PAYMENT;
DROP TABLE TB_REPORT_FEED;
DROP TABLE TB_FEED_BOOKMARK;
DROP TABLE TB_FEED_LIKE;
DROP TABLE TB_FEED_FILE;
DROP TABLE TB_FOLLOWS;
DROP TABLE TB_HOME_VISITOR;
DROP TABLE TB_DIARY;
DROP TABLE TB_STORY;
DROP TABLE TB_FEED;
DROP TABLE TB_MEMBER_HOME;
DROP TABLE TB_BGM;
DROP TABLE TB_MEMBER;

--------------------------------------------------------
-- 2. 모든 시퀀스 삭제
--------------------------------------------------------
DROP SEQUENCE SEQ_DIARY_NO;
DROP SEQUENCE SEQ_STORY_NO;
DROP SEQUENCE SEQ_REPORT_ID;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_GUESTBOOK_NO;
DROP SEQUENCE SEQ_DM_MESSAGE_ID;
DROP SEQUENCE SEQ_DM_ROOM_ID;
DROP SEQUENCE SEQ_PAYMENT_NO;
DROP SEQUENCE SEQ_BGM_NO;
DROP SEQUENCE SEQ_REPORT_FEED_ID;
DROP SEQUENCE SEQ_IMAGE_NO;
DROP SEQUENCE SEQ_FEED_NO;
DROP SEQUENCE SEQ_HOME_NO;
DROP SEQUENCE SEQ_COMMENT_LIKE_NO;
DROP SEQUENCE SEQ_BOOKMARK_NO;
DROP SEQUENCE SEQ_MEMBER_NO;

--------------------------------------------------------
-- 3. 시퀀스 생성
--------------------------------------------------------
CREATE SEQUENCE SEQ_HOME_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FEED_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_IMAGE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPORT_FEED_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BGM_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DM_ROOM_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DM_MESSAGE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GUESTBOOK_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPORT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_STORY_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DIARY_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_LIKE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOOKMARK_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------------
-- 4. 테이블 생성
--------------------------------------------------------

-- 1. 회원 테이블
CREATE TABLE TB_MEMBER (
    MEMBER_NO           NUMBER          PRIMARY KEY,
    MEMBER_ID           VARCHAR2(20)    UNIQUE NOT NULL,
    MEMBER_PWD          VARCHAR2(100)   NOT NULL,
    MEMBER_NAME         VARCHAR2(50)    NOT NULL,
    MEMBER_NICK         VARCHAR2(50)    UNIQUE,
    EMAIL               VARCHAR2(250)   UNIQUE,
    PHONE               VARCHAR2(13),
    GENDER              CHAR(1),
    BIRTHDAY            DATE,
    CREATE_DATE         DATE            DEFAULT SYSDATE,
    STATUS              CHAR(1)         DEFAULT 'N'
);

-- 2. 홈피 테이블
CREATE TABLE TB_MEMBER_HOME (
    HOME_NO             NUMBER          PRIMARY KEY,
    HOME_TITLE          VARCHAR2(50),
    STATUS_MSG          VARCHAR2(500),
    PROFILE_ORIGIN_NAME VARCHAR2(200),
    PROFILE_CHANGE_NAME VARCHAR2(200),
    IS_PRIVATE_PROFILE  CHAR(1)         DEFAULT 'N',
    IS_PRIVATE_VISIT    CHAR(1)         DEFAULT 'N',
    IS_PRIVATE_FOLLOW   CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          UNIQUE NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 3. 피드 테이블 (위치 관련 컬럼 통합 및 데이터타입 수정 반영)
CREATE TABLE TB_FEED (
    FEED_NO         NUMBER          PRIMARY KEY,
    CONTENT         VARCHAR2(200),
    TAG             VARCHAR2(20),
    LATITUDE        NUMBER(10,6),   -- 정밀 위도
    LONGITUDE       NUMBER(10,6),   -- 정밀 경도
    PLACE_NAME      VARCHAR2(100),  -- 장소명
    KAKAO_PLACE_ID  VARCHAR2(50),   -- 카카오 장소 ID
    ADDRESS_NAME    VARCHAR2(200),  -- 지번 주소
    ROAD_ADDRESS    VARCHAR2(200),  -- 도로명 주소
    CREATED_DATE    DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 피드 컬럼 추가(지도 이름)
ALTER TABLE TB_FEED
ADD LOCATION_NAME VARCHAR2(200);

-- 4. BGM 테이블
CREATE TABLE TB_BGM (
    BGM_NO           NUMBER          PRIMARY KEY,
    BGM_TITLE       VARCHAR2(200),
    FILE_PATH       VARCHAR2(250),
    ARTIST          VARCHAR2(100),
    PRICE           NUMBER,
    REG_DATE         DATE            DEFAULT SYSDATE
);

-- 5. DM 대화방 테이블
CREATE TABLE TB_DM_ROOM (   
    ROOM_ID         NUMBER          PRIMARY KEY, -- 원본 코드 일관성을 위해 ID 부여
    ROOM_TYPE       VARCHAR2(10)    DEFAULT 'PRIVATE', 
    ROOM_NAME       VARCHAR2(100), 
    CREATE_DATE     DATE            DEFAULT SYSDATE, 
    LAST_SEND_DATE  DATE            DEFAULT SYSDATE, 
    IS_DEL          CHAR(1)         DEFAULT 'N', 
    MEMBER_NO       NUMBER, 
    MEMBER_ID       VARCHAR2(20), 
    MEMBER_NAME     VARCHAR2(50)
);

-- 6. 스토리 테이블
CREATE TABLE TB_STORY (
    STORY_NO         NUMBER          PRIMARY KEY,
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    EXPIRE_DATE     DATE,
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(500),
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 7. 다이어리 테이블
CREATE TABLE TB_DIARY (
    DIARY_NO         NUMBER          PRIMARY KEY,
    TITLE           VARCHAR2(50),
    CONTENT         VARCHAR2(2100),
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(200),
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 8. 홈피 방문자 테이블
CREATE TABLE TB_HOME_VISITOR (
    VISIT_DATE      DATE            DEFAULT SYSDATE,
    MEMBER_NO       NUMBER          NOT NULL,
    HOME_NO         NUMBER          NOT NULL,
    PRIMARY KEY (MEMBER_NO, HOME_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 9. 팔로우 테이블
CREATE TABLE TB_FOLLOWS (
    MEMBER_NO       NUMBER          NOT NULL,
    HOME_NO         NUMBER          NOT NULL,
    PRIMARY KEY (MEMBER_NO, HOME_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 10. 피드 첨부 파일
CREATE TABLE TB_FEED_FILE (
    IMAGE_NO         NUMBER          PRIMARY KEY,
    ORIGIN_NAME     VARCHAR2(200),
    CHANGE_NAME     VARCHAR2(200),
    FILE_PATH       VARCHAR2(500),
    UPLOAD_DATE     DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    FEED_NO         NUMBER          NOT NULL,
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 11. 피드 좋아요
CREATE TABLE TB_FEED_LIKE (
    FEED_NO         NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    PRIMARY KEY (FEED_NO, MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 12. 피드 북마크
CREATE TABLE TB_FEED_BOOKMARK (
    BOOKMARK_NO     NUMBER          PRIMARY KEY,
    FEED_NO         NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 13. 피드 신고
CREATE TABLE TB_REPORT_FEED (
    REPORT_ID       NUMBER          PRIMARY KEY,
    REPORT_REASON   VARCHAR2(250),
    REPORT_DATE     DATE            DEFAULT SYSDATE,
    PROCESS_DATE    DATE,
    MEMBER_NO       NUMBER          NOT NULL,
    FEED_NO         NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 14. 결제 테이블
CREATE TABLE TB_PAYMENT (
    PAYMENT_NO      NUMBER          PRIMARY KEY,
    PAYMENT_AMOUNT  NUMBER,
    PAYMENT_DATE    DATE            DEFAULT SYSDATE,
    BGM_NO          NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    FOREIGN KEY (BGM_NO) REFERENCES TB_BGM(BGM_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 15. DM 메시지 테이블
CREATE TABLE TB_DM_MESSAGE (
    MESSAGE_ID      NUMBER          PRIMARY KEY,
    CONTENT         VARCHAR2(1500),
    SEND_DATE       DATE            DEFAULT SYSDATE,
    IS_READ         CHAR(1)         DEFAULT 'N',
    IS_DEL          CHAR(1)         DEFAULT 'N',
    MEMBER_NO       NUMBER          NOT NULL,  -- 보낸 회원
    MEMBER_NO2      NUMBER          NOT NULL,  -- 받은 회원
    ROOM_ID         NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (MEMBER_NO2) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (ROOM_ID) REFERENCES TB_DM_ROOM(ROOM_ID)
);

-- 16. 방명록 테이블
CREATE TABLE TB_GUESTBOOK (
    GUESTBOOK_NO        NUMBER          PRIMARY KEY,
    GUESTBOOK_CONTENT   VARCHAR2(4000)  NOT NULL,
    CREATE_DATE         DATE            DEFAULT SYSDATE,
    IS_DEL              CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          NOT NULL,
    HOME_NO             NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (HOME_NO) REFERENCES TB_MEMBER_HOME(HOME_NO)
);

-- 17. 방명록 좋아요
CREATE TABLE TB_GUESTBOOK_LIKE (
    MEMBER_NO       NUMBER          NOT NULL,
    GUESTBOOK_NO    NUMBER          NOT NULL,
    PRIMARY KEY (MEMBER_NO, GUESTBOOK_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (GUESTBOOK_NO) REFERENCES TB_GUESTBOOK(GUESTBOOK_NO)
);

-- 18. 댓글 테이블
CREATE TABLE TB_COMMENT (
    COMMENT_NO      NUMBER          PRIMARY KEY,
    CONTENT         VARCHAR2(250),
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    IS_DEL          CHAR(1)         DEFAULT 'N',
    WRITER          NUMBER          NOT NULL,
    FEED_NO         NUMBER          NOT NULL,
    FOREIGN KEY (WRITER) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (FEED_NO) REFERENCES TB_FEED(FEED_NO)
);

-- 19. 댓글 좋아요
CREATE TABLE TB_COMMENT_LIKE (
    COMMENT_LIKE_NO NUMBER          PRIMARY KEY,
    COMMENT_NO      NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    CREATE_DATE     DATE            DEFAULT SYSDATE,
    FOREIGN KEY (COMMENT_NO) REFERENCES TB_COMMENT(COMMENT_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO)
);

-- 20. 댓글 신고
CREATE TABLE TB_REPORT_COMMENT (
    REPORT_ID       NUMBER          PRIMARY KEY,
    REPORT_REASON   VARCHAR2(50),
    REPORT_DATE     DATE            DEFAULT SYSDATE,
    PROCESS_DATE    DATE,
    MEMBER_NO       NUMBER          NOT NULL,
    COMMENT_NO      NUMBER          NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (COMMENT_NO) REFERENCES TB_COMMENT(COMMENT_NO)
);

-- 21. 스토리 방문자 테이블
CREATE TABLE TB_STORY_VISITOR (
    MEMBER_NO       NUMBER          NOT NULL,
    STORY_NO        NUMBER          NOT NULL,
    PRIMARY KEY (MEMBER_NO, STORY_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (STORY_NO) REFERENCES TB_STORY(STORY_NO)
);