INSERT INTO TB_MEMBER (
    MEMBER_NO,
    MEMBER_ID,
    MEMBER_PWD,
    MEMBER_NAME,
    STATUS
) VALUES (
    SEQ_
    'test1',
    "$2a$10$zpNtFqus2QwHF4LfxyoAo.SpRjcnZlSS6hHf5hfzZYDvW7.7xdlie",
    '테스트유저',
    'Y'
);

CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

commit;

SELECT
  LENGTH(MEMBER_PWD) AS LEN,
  MEMBER_PWD
FROM TB_MEMBER
WHERE MEMBER_ID = 'test3';

SELECT MEMBER_ID, STATUS
FROM TB_MEMBER
WHERE MEMBER_ID = 'test3';



DROP TABLE TB_DM_ROOM;


-- 5. TB_DM_ROOM (DM 대화방 테이블)
CREATE TABLE TB_DM_ROOM (
    ROOM_ID             NUMBER          PRIMARY KEY,
    LAST_SEND_DATE      DATE,
    IS_DEL              CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          NOT NULL,  -- 방 만든 회원
    MEMBER_NO2          NUMBER          NOT NULL,  -- 초대된 회원

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (MEMBER_NO2) REFERENCES TB_MEMBER(MEMBER_NO)
);


BEGIN
  FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

SELECT MEMBER_PWD
FROM TB_MEMBER
WHERE MEMBER_ID = 'asdf123';


-- 스토리 테이블 추가(여러 사진 모음)
CREATE TABLE TB_STORY_ITEM (
  ITEM_NO      NUMBER        NOT NULL,
  STORY_NO     NUMBER        NOT NULL,
  ITEM_ORDER   NUMBER        NOT NULL,
  ORIGIN_NAME  VARCHAR2(200),
  CHANGE_NAME  VARCHAR2(200),
  FILE_PATH    VARCHAR2(500),
  STORY_TEXT   VARCHAR2(300),
  IS_DEL       CHAR(1) DEFAULT 'N' CHECK (IS_DEL IN ('Y','N')),
  CREATE_DATE  DATE DEFAULT SYSDATE,
  CONSTRAINT PK_STORY_ITEM PRIMARY KEY (ITEM_NO),
  CONSTRAINT FK_STORY_ITEM_STORY FOREIGN KEY (STORY_NO)
    REFERENCES TB_STORY (STORY_NO)
);

CREATE SEQUENCE SEQ_STORY_ITEM_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE TB_STORY_ITEM
  ADD CONSTRAINT UQ_STORY_ITEM_ORDER UNIQUE (STORY_NO, ITEM_ORDER);

COMMIT;

SELECT MAX(ITEM_NO);

SELECT NVL(MAX(ITEM_NO), 0) AS MAX_NO
FROM TB_STORY_ITEM;

-- 1. 시퀀스 삭제
DROP SEQUENCE SEQ_STORY_ITEM_NO;

-- 2. 시퀀스 재생성 (MAX + 1 = 6부터)
CREATE SEQUENCE SEQ_STORY_ITEM_NO
START WITH 6
INCREMENT BY 1
NOCACHE
NOCYCLE;


-- 1) 테이블 전체 최대 PK
SELECT MAX(ITEM_NO) FROM TB_STORY_ITEM;

-- 2) 지금 시퀀스가 어디까지 왔는지
SELECT SEQ_STORY_ITEM_NO.NEXTVAL FROM DUAL;

-- 3) 시퀀스 현재 상태(Last Number)
SELECT SEQUENCE_NAME, LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_STORY_ITEM_NO';



