INSERT INTO TB_MEMBER (
    MEMBER_NO,
    MEMBER_ID,
    MEMBER_PWD,
    MEMBER_NAME,
    STATUS
) VALUES (
    SEQ_
    'test1',
    "$2a$10$zpNtFqus2QwHF4LfxyoAo.SpRjcnZlSS6hHf5hfzZYDvW7.7xdlie",
    '테스트유저',
    'Y'
);

CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

commit;

SELECT
  LENGTH(MEMBER_PWD) AS LEN,
  MEMBER_PWD
FROM TB_MEMBER
WHERE MEMBER_ID = 'test3';

SELECT MEMBER_ID, STATUS
FROM TB_MEMBER
WHERE MEMBER_ID = 'test3';



DROP TABLE TB_DM_ROOM;


-- 5. TB_DM_ROOM (DM 대화방 테이블)
CREATE TABLE TB_DM_ROOM (
    ROOM_ID             NUMBER          PRIMARY KEY,
    LAST_SEND_DATE      DATE,
    IS_DEL              CHAR(1)         DEFAULT 'N',
    MEMBER_NO           NUMBER          NOT NULL,  -- 방 만든 회원
    MEMBER_NO2          NUMBER          NOT NULL,  -- 초대된 회원

    FOREIGN KEY (MEMBER_NO) REFERENCES TB_MEMBER(MEMBER_NO),
    FOREIGN KEY (MEMBER_NO2) REFERENCES TB_MEMBER(MEMBER_NO)
);


BEGIN
  FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

SELECT MEMBER_PWD
FROM TB_MEMBER
WHERE MEMBER_ID = 'asdf123';

