export const getChatWindowStyles = (theme) => ({
  chatContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: '#F7F7F7',
    fontFamily: 'sans-serif',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    padding: '15px 20px',
    backgroundColor: theme.primary,
    borderBottom: '1px solid #EEEEEE',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.05)',
    transition: 'background-color 0.3s ease',
  },
  backButton: {
    fontSize: '24px',
    marginRight: '15px',
    cursor: 'pointer',
    color: '#333333',
  },
  profileImage: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    objectFit: 'cover',
    marginRight: '10px',
    backgroundColor: theme.primary,
  },
  username: {
    fontWeight: '600',
    fontSize: '16px',
    color: '#333333',
  },
  messageArea: {
    flexGrow: '1',
    padding: '20px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  },
  inputArea: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 20px',
    borderTop: '1px solid #EEEEEE',
    backgroundColor: 'white',
  },
  input: {
    flex: 1,
    padding: '10px 15px',
    border: `1px solid ${theme.primary}`,
    borderRadius: '20px',
    fontSize: '14px',
    outline: 'none',
    fontFamily: 'sans-serif',
    transition: 'border-color 0.3s ease',
  },
  sendButton: {
    marginLeft: '10px',
    fontSize: '24px',
    cursor: 'pointer',
    color: theme.primary,
    backgroundColor: 'transparent',
    border: 'none',
  },
});
