export const getChatListStyles = (theme) => ({
  chatListContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: 'white',
    fontFamily: 'sans-serif',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '15px 20px',
    borderBottom: '1px solid #EEEEEE',
    transition: 'background-color 0.3s ease',
  },
  title: {
    fontWeight: '700',
    fontSize: '20px',
    color: '#333333',
  },
  icon: {
    fontSize: '24px',
    color: '#999999',
    cursor: 'pointer',
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 20px 0 20px',
    backgroundColor: 'white',
  },
  searchInput: {
    flex: 1,
    padding: '10px 12px',
    border: '1px solid #E5E5E5',
    borderRadius: '12px',
    fontSize: '14px',
    outline: 'none',
  },
  searchCancel: {
    border: 'none',
    background: 'transparent',
    color: '#999',
    cursor: 'pointer',
    fontSize: '14px',
  },
  list: {
    overflowY: 'auto',
    flex: 1,
  },
  listItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '15px 20px',
    borderBottom: '1px solid #F0F0F0',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  listItemHover: {
    backgroundColor: theme.primary,
    opacity: 0.3,
  },
  profileImage: {
    width: '50px',
    height: '50px',
    borderRadius: '50%',
    objectFit: 'cover',
    marginRight: '15px',
  },
  content: {
    flex: 1,
    minWidth: 0,
  },
  name: {
    fontWeight: '600',
    fontSize: '15px',
    color: '#333333',
    marginBottom: '5px',
  },
  preview: {
    fontSize: '14px',
    color: '#999999',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  badge: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    backgroundColor: theme.badge,
    color: '#333333',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '12px',
    fontWeight: 'bold',
  },
  themeSelector: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: '10px 20px',
    backgroundColor: '#F5F5F5',
    borderTop: '1px solid #EEEEEE',
    gap: '10px',
    position: 'sticky',
    bottom: 0,
    zIndex: 1,
  },
  themeButton: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
    transition: 'transform 0.2s, box-shadow 0.2s',
  },
  themeButtonActive: {
    boxShadow: '0 0 0 3px #333333',
  },
});
