export const getOverlayStyles = (theme) => ({
  container: {
    position: 'fixed',
    width: '360px',
    height: '560px',
    minWidth: '360px',
    minHeight: '560px',
    zIndex: 9999,
    borderRadius: '16px',
    boxShadow: '0 12px 30px rgba(0,0,0,0.18)',
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '44px',
    padding: '0 10px',
    backgroundColor: theme.primary,
    cursor: 'move',
    userSelect: 'none',
  },
  title: {
    fontWeight: 600,
    fontSize: '14px',
    color: '#333333',
  },
  controls: {
    display: 'flex',
    gap: '8px',
  },
  controlBtn: {
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    border: 'none',
    backgroundColor: 'rgba(255,255,255,0.7)',
    color: '#333333',
    cursor: 'pointer',
  },
  body: {
    width: '100%',
    height: 'calc(100% - 44px)',
    backgroundColor: '#F7F7F7',
  },
  resizeHandle: {
    position: 'absolute',
    width: '16px',
    height: '16px',
    right: '4px',
    bottom: '4px',
    cursor: 'nwse-resize',
    background: 'linear-gradient(135deg, transparent 50%, rgba(0,0,0,0.12) 50%)',
    borderRadius: '4px',
  },
});
